pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
 }
 stages {
 	stage ('Build'){
 		steps {
    
      withMaven(maven:'my_maven'){
 			
 			bat 'mvn -f mygitproject/pom.xml clean install'
 			
 		}
   }
 	}
 	stage ('Deploy'){
 		steps {
   
       withMaven(maven:'my_maven'){
 			
 			   	bat 'mvn -f mygitproject/pom.xml package deploy  -Dusername=praveenD -Dpassword=Ultimo2860 -Denvironment=SANDBOX -DmuleDeploy'
 			
 		}
 	}
 }

}
}
